# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeProject' do
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeProject
  # Use the following line to use App Center Analytics and Crashes.
  

  # Use the following lines if you want to specify which service you want to use.
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Distribute'
  pod 'AppCenter/Push'

  platform :ios, '9.0'
  target 'AwesomeProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwesomeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AwesomeProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
